require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe RefclinicasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Refclinica. As you add validations to Refclinica, be sure to
  # adjust the attributes here as well.
  let(:patient) {FactoryBot.create(:patient, :active)}
  let(:valid_attributes) {
    # FactoryBot.attributes_for(:patient)
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RefclinicasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Refclinica.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      refclinica = Refclinica.create! valid_attributes
      get :show, params: {id: refclinica.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
  before do
    FactoryBot.attributes_for(:patient)
  end
    # it "returns a success response" do
      # get :new, params: { patient_id: patient.id }, session: valid_session
      # expect(response).to be_successful
    # end
    ## Shorter version with shoulda matchers
    it { is_expected.to route(:get, "/patients/#{patient.id}/refclinicas/new").to(action: :new,  patient_id: patient.id) }
  end

  describe "GET #edit" do
    it "returns a success response" do
      refclinica = Refclinica.create! valid_attributes
      get :edit, params: {id: refclinica.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Refclinica" do
        expect {
          post :create, params: {refclinica: valid_attributes}, session: valid_session
        }.to change(Refclinica, :count).by(1)
      end

      it "redirects to the created refclinica" do
        post :create, params: {refclinica: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Refclinica.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {refclinica: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested refclinica" do
        refclinica = Refclinica.create! valid_attributes
        put :update, params: {id: refclinica.to_param, refclinica: new_attributes}, session: valid_session
        refclinica.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the refclinica" do
        refclinica = Refclinica.create! valid_attributes
        put :update, params: {id: refclinica.to_param, refclinica: valid_attributes}, session: valid_session
        expect(response).to redirect_to(refclinica)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        refclinica = Refclinica.create! valid_attributes
        put :update, params: {id: refclinica.to_param, refclinica: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested refclinica" do
      refclinica = Refclinica.create! valid_attributes
      expect {
        delete :destroy, params: {id: refclinica.to_param}, session: valid_session
      }.to change(Refclinica, :count).by(-1)
    end

    it "redirects to the refclinicas list" do
      refclinica = Refclinica.create! valid_attributes
      delete :destroy, params: {id: refclinica.to_param}, session: valid_session
      expect(response).to redirect_to(refclinicas_url)
    end
  end

end
